Global:
  device: gpu
  epoch_num: 60
  log_smooth_window: 20
  print_batch_step: 10
  output_dir: ./output/rec/svtr_base666_cppd/
  save_epoch_step: 1
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 500]
  eval_epoch_step: [0, 1]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints: ./output/rec/svtr_base666_cppd/best.pth
  use_tensorboard: false
  infer_img: ../dataset/test
  # for data or label process
  character_dict_path: &character_dict_path ./tools/utils/EN_symbol_dict.txt # 96en
  # ./tools/utils/ppocr_keys_v1.txt  # ch
  max_text_length: &max_text_length 25
  use_space_char: &use_space_char False
  save_res_path: ./output/rec/predicts_cppd.txt
  use_amp: True

Optimizer:
  name: AdamW
  lr: 0.0005
  weight_decay: 0.05
  filter_bias_and_bn: True

LRScheduler:
  name: CosineAnnealingLR
  warmup_epoch: 2

Architecture:
  model_type: rec
  algorithm: BGPD
  in_channels: 3
  Transform:
  Encoder:
    name: SVTRNet
    img_size: [32, 100]
    out_char_num: 25 # W//4 or W//8 or W/12s
    out_channels: 192
    patch_merging: "Conv"
    embed_dim: [64, 128, 256]
    depth: [3, 6, 3]
    num_heads: [2, 4, 8]
    mixer:
      [
        "Local",
        "Local",
        "Local",
        "Local",
        "Local",
        "Local",
        "Global",
        "Global",
        "Global",
        "Global",
        "Global",
        "Global",
      ]
    local_mixer: [[7, 11], [7, 11], [7, 11]]
    last_stage: False
    prenorm: True
  Decoder:
    name: CPPDDecoder
    vis_seq: 50
    num_layer: 3
    pos_len: False
    rec_layer: 1

Loss:
  name: CPPDLoss
  ignore_index: 100
  smoothing: True
  pos_len: False
  sideloss_weight: 1.0

PostProcess:
  name: CPPDLabelDecode
  character_dict_path: *character_dict_path
  use_space_char: *use_space_char

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ../dataset/mini5000
    label_file_list:
      - ../dataset/mini5000/gt.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      #   - SVTRRAug:
      - CPPDLabelEncode: # Class handling label
          pos_len: False
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - SVTRResize:
          image_shape: [3, 32, 100]
          padding: False
      - KeepKeys:
          keep_keys: ["image", "label", "label_node", "length"] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 64
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ../dataset/mini1250
    label_file_list:
      - ../dataset/mini1250/gt.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CPPDLabelEncode: # Class handling label
          pos_len: False
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - SVTRResize:
          image_shape: [3, 32, 100]
          padding: False
      - KeepKeys:
          keep_keys: ["image", "label", "label_node", "length"] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 32
    num_workers: 2

MLFlow:
  mlflow_run_name: svtr_base_cppd
  model_type: svtr_cppd_rec
  experiment_name: torch-svtr-cppd